import maya.cmds as cmds
cmds.file(f=True, new=True)
#étape 1: create a path, e,g, a curve
path = cmds.curve(n='curve1',d=3,p=[(-10, 0, 0),(5, 0, 15),(1, 0, -10),(10, 2, 0)],k=[0, 0, 0, 1, 1, 1])
closedCurve = cmds.closeCurve( 'curve1', ch=True, ps=True, rpo = True )
duplicatedCurve = cmds.duplicateCurve( closedCurve, ch=False )
cmds.scale( 2, 2, 2, duplicatedCurve, pivot=(1, 0, 0), absolute=True )
cmds.loft(closedCurve, duplicatedCurve, ch=True, rn=True, ar=True, n='loftToConvert' )
cmds.nurbsToPoly('loftToConvert')
cmds.hide('loftToConvert')
#repeat and play:
mypath1 = cmds.curve(d = 1, p = [(12,0,12),(12,0,-12),(-12,0,-12),(-12,0,12),(12,0,12)])
duplicatedCurve2 = cmds.duplicateCurve( mypath1, ch=False )
cmds.scale( 1.3, 1.3, 1.3, duplicatedCurve2, pivot=(1, 0, 0), absolute=True )
cmds.loft(mypath1, duplicatedCurve2, ch=True, rn=True, ar=True, n='loftToConvert2' )
cmds.nurbsToPoly('loftToConvert2')
mypath2 = cmds.curve(d = 1, p = [(10,0,10),(10,0,-10),(-10,0,-10),(-10,0,10),(10,0,10)])
duplicatedCurve3 = cmds.duplicateCurve( mypath2, ch=False )
cmds.scale( 1.2, 1.2, 1.2, duplicatedCurve3, pivot=(1, 0, 0), absolute=True )
cmds.loft(mypath2, duplicatedCurve3, ch=True, rn=True, ar=True, n='loftToConvert3' )
cmds.nurbsToPoly('loftToConvert3')
cmds.hide('loftToConvert')
cmds.hide('loftToConvert2')
cmds.hide('loftToConvert3')
#étape 2: create objs et anim avec le curve

#mypath3 = cmds.curve(d = 1, p = [(8,0,8),(8,0,-8),(-8,0,-8),(-8,0,8),(8,0,8)])
myCube1 = cmds.polyCube(w = 0.1,h=0.1)
myCar1 = cmds.file( 'F:\ATI\2021\courPython2\TP_Group_2021\Car_4x4_.fbx', i = True, type = 'fbx')  
myCar2 = cmds.file( 'F:\ATI\2021\courPython2\TP_Group_2021\car_normal.fbx', i = True, type = 'fbx')  
myCube2 = cmds.polyCube(w = 0.1, h=0.1)
parentedO = cmds.parent('Car_4x4',myCube1, add=True)
parented1 = cmds.parent('car_normal',myCube2, add=True)
#with path animation:
cmds.pathAnimation(parentedO[0], c=mypath1, stu = 0, etu = 120, f = True )
cmds.pathAnimation(parented1[0], c=path, stu = 20, etu = 120, f = True )
#---------------------------------------------------------------------------------------
#with keyFrame:
cmds.currentTime(1)
#we select the curve point WIP:
curveAtt = cmds.getAttr( 'curve1.cv[*]' )
print(curveAtt)
car3 = cmds.duplicate(parented1)
cmds.currentTime(1)
cmds.setKeyframe( v=-10, at='translateX' )
# curveAtt1 = cmds.getAttr( 'curve1.cv[1:0]' )
cmds.currentTime(50)
cmds.setKeyframe( v=0, at='translateX' )
cmds.setKeyframe( v=15, at='translateZ' )
cmds.currentTime(120)
# curveAtt2 = cmds.getAttr( 'curve1.cv[2:0]' )
cmds.setKeyframe( v=10, at='translateX' )
cmds.setKeyframe( v=-10, at='translateZ' )